### PR TITLE
Allow passing in props via the query

### PR DESCRIPTION
**Pull request by joshwnj**
Thought it would be nice to be able to pass in props. Let me know if this is the best way to go about it, I'm not familiar with webpack.

### CODE REVIEW

**Comment by joshwnj** [comment]
PS. a following pr is coming that incorporates this into `reactview` :)

**Comment by zackify** [comment]
@joshwnj thanks for the help, this was actually something i planned on after doing the hot reloading feature! I'm going to pull this and test. How did you find this repo btw.

**Comment by zackify** [comment]
When you make your pr on reactview, change it to version 1.1.0 of this :)

**Comment by joshwnj** [comment]
Thanks - done: https://github.com/zackify/reactview/pull/3

I came across this repo when poking around reactview source, and I saw reactview in Twitter.

**Pull request merged**
