### PR TITLE
Hackishly load exported component

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by zackify** [comment]
That's a beautiful hack. I'm just going to check it over in the morning. If you could bump the package.json version that would be great too. Idk why I have it at 1.1 already :P

**Comment by taion** [comment]
Done. This is technically a breaking change, so semver requires 2.0.

**Comment by zackify** [comment]
Cool, I'll merge and update reactview after testing it out!

**Comment by zackify** [comment]
Using this with reactview throws an error: `type.toUpperCase is not a function` when try 
screen shot 2015-05-15 at 3 09 51 pm using the example component.

**Comment by taion** [comment]
You'll need to export the component. The idea is that this makes it render whatever component gets exported (either with `module.exports` or ES6-style `export default`).

**Comment by zackify** [comment]
@taion sorry I thought I had it exported, dumb mistake!

**Pull request merged**
